# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [2]:
# importing the NumPy library

import numpy as np

In [7]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = np.arange(1, 10, 2)


# creating an array of zeroes with 5 elements
np_2 = np.zeros(5)

In [8]:
# checking the created array: np_1
print(np_1)

[1 3 5 7 9]


In [9]:
# checking the created array:np_2
print(np_2)

[0. 0. 0. 0. 0.]


In [10]:
# data type of np_2
np_2.dtype

dtype('float64')

In [11]:
# specifying the data type of the array in the provided attribute
np_2 = np.zeros(5, dtype='int')
np_2.dtype


dtype('int32')

In [12]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

[1 3 5 7 9]


In [15]:
# check the dimension of the arrays
# array np_1
np_1.ndim

1

In [16]:
# check the dimension of the arrays
# array np_2
np_2.ndim

1

In [18]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(5, dtype='int')

# checking the created array:np_3
print(np_3)

[1 1 1 1 1]


In [29]:
# check the dimension of the arrays
# array np_2
np_3.ndim

1

In [30]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

[-1 -1 -1 -1 -1]


In [31]:
# creating an array of fixed length
np_4 = np.linspace(1, 10)

# checking the created array:np_4
print(np_4)
np_4.shape

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


(50,)

In [32]:
# checking the created array:np_1
np_1

array([1, 3, 5, 7, 9])

In [45]:
# squaring the terms of np_1
np.power(np_1, 2)

array([ 1,  9, 25, 49, 81], dtype=int32)

### Create border array
#### Description
Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

Note: Make sure the array is of type int.


In [37]:
np_5 = np.ones((4,4), dtype = 'int')
np_5

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np_6 = np.zeros((2,2), dtype='int')
np_6

array([[0, 0],
       [0, 0]])

In [43]:
np_5[1:3,1:3]=np_5[1:3,1:3]*np_6
np_5

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [44]:
n = 5
border_array = np.ones((n,n), dtype='int')
border_array[1:-1,1:-1] = border_array[1:-1,1:-1]*0
border_array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [46]:
# getting the absolute value of the elements
np.absolute([1, 2, -1, -2])

array([1, 2, 1, 2])

In [ ]:
# np.sin()
# np.cos()

In [ ]:
# np.log()

### Empty arrays

In [47]:
# Creating empty arrays

x = np.arange(1, 6)
y = np.empty(5)

# filling the empty array
y = x * y

In [48]:
# printing the output obtained above
y

array([1., 2., 3., 4., 5.])

### Swap two rows
#### Description
Given m and n, swap the mth and nth rows of the 2-D NumPy array given below.

In [65]:
m = 0
n = 2
a = [[4, 3, 1],
     [5, 7, 0],
     [9, 9, 3],
     [8, 2, 4]]
np_a = np.array(a)
print(np_a)
np_a[[n,m]]=np_a[[m,n]]
print(np_a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


### Aggregation of array elements

In [71]:
# Reducing the elements to a single value based on addition
np_a = np.array([1,2,3,4,5])
np.add.reduce(np_a)

15

In [72]:
# Cummulative addition of elements at each element
np.add.accumulate(np_a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [73]:
np.linalg

<module 'numpy.linalg' from 'C:\\Users\\prate\\anaconda3\\lib\\site-packages\\numpy\\linalg\\__init__.py'>

In [13]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

### Checkerboard Matrix
#### Description
Given an even integer ‘n’, create an ‘n*n’ checkerboard matrix with the values 0 and 1, using the tile function.
 
#### Format:
#### Input: A single even integer 'n'.
#### Output: An 'n*n' NumPy array in checkerboard format.

In [80]:
n=4
np_a = np.array([[0,1],
                 [1,0]])
if n == 2:
    print(np_a)
else:
    n = n//2
    np_b = np.tile(np_a,(n,n))
    print(np_b)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [81]:
# Create the smallest unit of a checkerboard matrix
x = np.array([[0, 1], [1, 0]])

# Create a checkerboard matrix of size n*n using the tile() function. We use n//2 
# since the smallest unit of a checkerboard matrix is already of size 2*2. So, for 
# creating a larger matrix, say, of size 8, we need to replicate it using the tile()
# function 4 times as it will then give a matrix of size 8*8.
check = np.tile(x, (n//2, n//2))

# Print the created matrix
print(check)

[[0 1]
 [1 0]]


## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [3]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [4]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type here is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [5]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [6]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 3])

array([[0.58682568, 0.33906324, 0.78317791],
       [0.64641231, 0.26468618, 0.81324413],
       [0.15391479, 0.4718496 , 0.36771618]])

In [9]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[6, 2, 1, 4],
       [9, 7, 2, 8],
       [2, 1, 4, 3],
       [3, 7, 3, 8]])